macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  skip: "changesIncludeOnly('**.md')"
  env:
    GRAALVM_HOME: ${HOME}/graalvm-ce-java11-22.2.0/Contents/Home
  script: |
    sudo .circleci/script/install-clojure
    curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.2.0/graalvm-ce-java11-darwin-aarch64-22.2.0.tar.gz
    tar xzf graalvm-ce-java11-darwin-aarch64-22.2.0.tar.gz
    $GRAALVM_HOME/bin/gu install native-image
    export PATH=$GRAALVM_HOME/bin:$PATH
    sudo /usr/sbin/softwareupdate --install-rosetta --agree-to-license
    java -version
    make package-m1 GRAALVM_HOME=$GRAALVM_HOME STATIC=false
  binaries_artifacts:
    path: build
