macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  skip: "changesIncludeOnly('**.md')"
  env:
    GRAALVM_HOME: ${HOME}/graalvm-jdk-21.0.1+12.1/Contents/Home
  script: |
    sudo .circleci/script/install-clojure /usr/local/
    curl -O -sL https://download.oracle.com/graalvm/21/archive/graalvm-jdk-21.0.1_macos-aarch64_bin.tar.gz
    tar -C $HOME -xf graalvm-jdk-21.0.1_macos-aarch64_bin.tar.gz
    export PATH=$GRAALVM_HOME/bin:$PATH
    sudo /usr/sbin/softwareupdate --install-rosetta --agree-to-license
    java -version
    make package-m1 GRAALVM_HOME=$GRAALVM_HOME STATIC=false
  binaries_artifacts:
    path: "dist/*"
