/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BbsshUtils */

#ifndef _Included_BbsshUtils
#define _Included_BbsshUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BbsshUtils
 * Method:    is_stdout_a_tty
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BbsshUtils_is_1stdout_1a_1tty
  (JNIEnv *, jclass);

/*
 * Class:     BbsshUtils
 * Method:    get_terminal_width
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BbsshUtils_get_1terminal_1width
  (JNIEnv *, jclass);

/*
 * Class:     BbsshUtils
 * Method:    get_terminal_height
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BbsshUtils_get_1terminal_1height
  (JNIEnv *, jclass);

/*
 * Class:     BbsshUtils
 * Method:    enter_raw_mode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_BbsshUtils_enter_1raw_1mode
  (JNIEnv *, jclass, jint);

/*
 * Class:     BbsshUtils
 * Method:    leave_raw_mode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_BbsshUtils_leave_1raw_1mode
  (JNIEnv *, jclass, jint);

/*
 * Class:     BbsshUtils
 * Method:    ssh_open_auth_socket
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_BbsshUtils_ssh_1open_1auth_1socket
  (JNIEnv *, jclass, jstring);

/*
 * Class:     BbsshUtils
 * Method:    ssh_close_auth_socket
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_BbsshUtils_ssh_1close_1auth_1socket
  (JNIEnv *, jclass, jint);

/*
 * Class:     BbsshUtils
 * Method:    ssh_auth_socket_read
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_BbsshUtils_ssh_1auth_1socket_1read
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     BbsshUtils
 * Method:    ssh_auth_socket_write
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_BbsshUtils_ssh_1auth_1socket_1write
  (JNIEnv *, jclass, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
